// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Teste-4.3_NaviSmart_UI

#ifndef UI_SCREENRACE_H
#define UI_SCREENRACE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenRace
extern void ui_ScreenRace_screen_init(void);
extern void ui_ScreenRace_screen_destroy(void);
extern lv_obj_t *ui_ScreenRace;
extern lv_obj_t *ui_PanelHeader;
extern lv_obj_t *ui_ValTime;
extern lv_obj_t *ui_ValTimer;
extern lv_obj_t *ui_ValBattery;
extern lv_obj_t *ui_PanelTop;
extern lv_obj_t *ui_ValHDG;
extern lv_obj_t *ui_LblHDG;
extern lv_obj_t *ui_PanelSpeed;
extern lv_obj_t *ui_ValKTS;
extern lv_obj_t *ui_LblKTS;
extern lv_obj_t *ui_PanelBottom;
extern lv_obj_t *ui_heel;
extern lv_obj_t *ui_ValHEEL;
extern lv_obj_t *ui_LblHEEL;
extern lv_obj_t *ui_LinhaSeparadora;
extern lv_obj_t *ui_trim;
extern lv_obj_t *ui_ValTRIM;
extern lv_obj_t *ui_LblTRIM;
// CUSTOM VARIABLES
extern lv_obj_t *uic_LblHDG;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

