// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Teste-4.3_NaviSmart_UI

#ifndef UI_SCREENSTART_H
#define UI_SCREENSTART_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenStart
extern void ui_ScreenStart_screen_init(void);
extern void ui_ScreenStart_screen_destroy(void);
extern lv_obj_t *ui_ScreenStart;
extern lv_obj_t *ui_PanelHeader1;
extern lv_obj_t *ui_ValTimeS;
extern lv_obj_t *ui_Name;
extern lv_obj_t *ui_ValBatteryS;
extern lv_obj_t *ui_PanelFooter;
extern lv_obj_t *ui_LabelWarnSD;
extern lv_obj_t *ui_LabelPowerOff;
extern lv_obj_t *ui_PanelSD;
extern lv_obj_t *ui_SdReady;
extern lv_obj_t *ui_SymSD;
extern lv_obj_t *ui_Panel7;
extern lv_obj_t *ui_SymPlay;
extern lv_obj_t *ui_Press;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

