// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Teste-4.3_NaviSmart_UI

#ifndef _TESTE_4_3_NAVISMART_UI_UI_H
#define _TESTE_4_3_NAVISMART_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_ScreenStart.h"
#include "ui_ScreenRace.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// FONTS
LV_FONT_DECLARE( ui_font_MontBold150);
LV_FONT_DECLARE( ui_font_MontBold200);
LV_FONT_DECLARE( ui_font_MontBold230);
LV_FONT_DECLARE( ui_font_MontBold26);
LV_FONT_DECLARE( ui_font_MontBold34);
LV_FONT_DECLARE( ui_font_Roboto200);
LV_FONT_DECLARE( ui_font_MontBold180);
LV_FONT_DECLARE( ui_font_MontBold130);
LV_FONT_DECLARE( ui_font_OswaldM220);
LV_FONT_DECLARE( ui_font_OswaldM250);
LV_FONT_DECLARE( ui_font_OswaldM160);
LV_FONT_DECLARE( ui_font_OswaldM24);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
