// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Teste-4.3_NaviSmart_UI

#include "ui.h"

lv_obj_t *ui_ScreenStart = NULL;lv_obj_t *ui_PanelHeader1 = NULL;lv_obj_t *ui_ValTimeS = NULL;lv_obj_t *ui_Name = NULL;lv_obj_t *ui_ValBatteryS = NULL;lv_obj_t *ui_PanelFooter = NULL;lv_obj_t *ui_LabelWarnSD = NULL;lv_obj_t *ui_LabelPowerOff = NULL;lv_obj_t *ui_PanelSD = NULL;lv_obj_t *ui_SdReady = NULL;lv_obj_t *ui_SymSD = NULL;lv_obj_t *ui_Panel7 = NULL;lv_obj_t *ui_SymPlay = NULL;lv_obj_t *ui_Press = NULL;
// event funtions

// build funtions

void ui_ScreenStart_screen_init(void)
{
ui_ScreenStart = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenStart, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ScreenStart, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenStart, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelHeader1 = lv_obj_create(ui_ScreenStart);
lv_obj_set_height( ui_PanelHeader1, 40);
lv_obj_set_width( ui_PanelHeader1, lv_pct(100));
lv_obj_clear_flag( ui_PanelHeader1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_PanelHeader1, lv_color_hex(0xBAB7B7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelHeader1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_PanelHeader1, LV_BORDER_SIDE_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Name = lv_label_create(ui_PanelHeader1);
lv_obj_set_width( ui_Name, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Name, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Name, LV_ALIGN_CENTER );
lv_label_set_text(ui_Name,"NaviSmart");
lv_obj_set_style_text_color(ui_Name, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Name, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Name, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelFooter = lv_obj_create(ui_ScreenStart);
lv_obj_set_height( ui_PanelFooter, 180);
lv_obj_set_width( ui_PanelFooter, lv_pct(100));
lv_obj_set_align( ui_PanelFooter, LV_ALIGN_BOTTOM_MID );
lv_obj_set_flex_flow(ui_PanelFooter,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_PanelFooter, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_PanelFooter, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_PanelFooter, lv_color_hex(0x111111), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelFooter, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_PanelFooter, LV_BORDER_SIDE_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_PanelFooter, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PanelFooter, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PanelFooter, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PanelFooter, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelWarnSD = lv_label_create(ui_PanelFooter);
lv_obj_set_width( ui_LabelWarnSD, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelWarnSD, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelWarnSD, 0 );
lv_obj_set_y( ui_LabelWarnSD, -25 );
lv_obj_set_align( ui_LabelWarnSD, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelWarnSD," Hold 3s to Turn Off");
lv_obj_set_style_text_color(ui_LabelWarnSD, lv_color_hex(0x7A7A7A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelWarnSD, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelWarnSD, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPowerOff = lv_label_create(ui_PanelFooter);
lv_obj_set_width( ui_LabelPowerOff, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPowerOff, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelPowerOff, 0 );
lv_obj_set_y( ui_LabelPowerOff, 5 );
lv_obj_set_align( ui_LabelPowerOff, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPowerOff," Power Off before removing SD");
lv_obj_set_style_text_color(ui_LabelPowerOff, lv_color_hex(0x7A7A7A), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPowerOff, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPowerOff, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelSD = lv_obj_create(ui_ScreenStart);
lv_obj_set_width( ui_PanelSD, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_PanelSD, LV_SIZE_CONTENT);   /// 50
lv_obj_set_x( ui_PanelSD, 0 );
lv_obj_set_y( ui_PanelSD, 80 );
lv_obj_set_align( ui_PanelSD, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PanelSD,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_PanelSD, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_PanelSD, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_PanelSD, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelSD, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_PanelSD, LV_BORDER_SIDE_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_PanelSD, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_PanelSD, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SdReady = lv_label_create(ui_PanelSD);
lv_obj_set_width( ui_SdReady, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SdReady, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SdReady, -10 );
lv_obj_set_y( ui_SdReady, 43 );
lv_obj_set_align( ui_SdReady, LV_ALIGN_CENTER );
lv_label_set_text(ui_SdReady,"SD Card Ready");
lv_obj_set_style_text_decor(ui_SdReady, LV_TEXT_DECOR_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SdReady, &ui_font_MontBold26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SymSD = lv_label_create(ui_PanelSD);
lv_obj_set_width( ui_SymSD, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SymSD, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SymSD, LV_ALIGN_CENTER );
lv_label_set_text(ui_SymSD,"");
lv_obj_set_style_text_font(ui_SymSD, &lv_font_montserrat_32, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel7 = lv_obj_create(ui_ScreenStart);
lv_obj_set_width( ui_Panel7, 220);
lv_obj_set_height( ui_Panel7, 220);
lv_obj_set_x( ui_Panel7, 0 );
lv_obj_set_y( ui_Panel7, -180 );
lv_obj_set_align( ui_Panel7, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel7, 150, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel7, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel7, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SymPlay = lv_label_create(ui_Panel7);
lv_obj_set_width( ui_SymPlay, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SymPlay, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SymPlay, LV_ALIGN_CENTER );
lv_label_set_text(ui_SymPlay,"");
lv_obj_set_style_text_color(ui_SymPlay, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SymPlay, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SymPlay, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Press = lv_label_create(ui_ScreenStart);
lv_obj_set_width( ui_Press, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Press, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Press, -1 );
lv_obj_set_y( ui_Press, -40 );
lv_obj_set_align( ui_Press, LV_ALIGN_CENTER );
lv_label_set_text(ui_Press,"Press Button to Start");
lv_obj_set_style_text_color(ui_Press, lv_color_hex(0xBAB7B7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Press, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Press, &lv_font_montserrat_22, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_ScreenStart_screen_destroy(void)
{
   if (ui_ScreenStart) lv_obj_del(ui_ScreenStart);

// NULL screen variables
ui_ScreenStart= NULL;
ui_PanelHeader1= NULL;
ui_ValTimeS= NULL;
ui_Name= NULL;
ui_ValBatteryS= NULL;
ui_PanelFooter= NULL;
ui_LabelWarnSD= NULL;
ui_LabelPowerOff= NULL;
ui_PanelSD= NULL;
ui_SdReady= NULL;
ui_SymSD= NULL;
ui_Panel7= NULL;
ui_SymPlay= NULL;
ui_Press= NULL;

}
