// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: Teste-4.3_NaviSmart_UI

#include "ui.h"

lv_obj_t *uic_LblHDG;
lv_obj_t *ui_ScreenRace = NULL;lv_obj_t *ui_PanelHeader = NULL;lv_obj_t *ui_ValTime = NULL;lv_obj_t *ui_ValTimer = NULL;lv_obj_t *ui_ValBattery = NULL;lv_obj_t *ui_PanelTop = NULL;lv_obj_t *ui_ValHDG = NULL;lv_obj_t *ui_LblHDG = NULL;lv_obj_t *ui_PanelSpeed = NULL;lv_obj_t *ui_ValKTS = NULL;lv_obj_t *ui_LblKTS = NULL;lv_obj_t *ui_PanelBottom = NULL;lv_obj_t *ui_heel = NULL;lv_obj_t *ui_ValHEEL = NULL;lv_obj_t *ui_LblHEEL = NULL;lv_obj_t *ui_LinhaSeparadora = NULL;lv_obj_t *ui_trim = NULL;lv_obj_t *ui_ValTRIM = NULL;lv_obj_t *ui_LblTRIM = NULL;
// event funtions

// build funtions

void ui_ScreenRace_screen_init(void)
{
ui_ScreenRace = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenRace, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_ScreenRace,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_ScreenRace, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_set_style_bg_color(ui_ScreenRace, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenRace, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_ScreenRace, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_ScreenRace, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_ScreenRace, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_ScreenRace, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_ScreenRace, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_ScreenRace, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelHeader = lv_obj_create(ui_ScreenRace);
lv_obj_set_height( ui_PanelHeader, 40);
lv_obj_set_width( ui_PanelHeader, lv_pct(100));
lv_obj_clear_flag( ui_PanelHeader, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_PanelHeader, lv_color_hex(0xBAB7B7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelHeader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ValTimer = lv_label_create(ui_PanelHeader); //alterado aqui cronometro
lv_obj_set_width( ui_ValTimer, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ValTimer, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ValTimer, LV_ALIGN_CENTER );
lv_label_set_text(ui_ValTimer,"00:00:00");
lv_obj_set_style_text_color(ui_ValTimer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ValTimer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ValTimer, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelTop = lv_obj_create(ui_ScreenRace);
lv_obj_set_height( ui_PanelTop, 265);
lv_obj_set_width( ui_PanelTop, lv_pct(100));
lv_obj_set_x( ui_PanelTop, -1 );
lv_obj_set_y( ui_PanelTop, lv_pct(-29) );
lv_obj_set_align( ui_PanelTop, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelTop, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_PanelTop, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelTop, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_PanelTop, LV_BORDER_SIDE_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ValHDG = lv_label_create(ui_PanelTop);
lv_obj_set_width( ui_ValHDG, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ValHDG, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ValHDG, -5 );
lv_obj_set_y( ui_ValHDG, 1 );
lv_obj_set_align( ui_ValHDG, LV_ALIGN_CENTER );
lv_label_set_text(ui_ValHDG,"246");
lv_obj_set_style_text_color(ui_ValHDG, lv_color_hex(0xBAB7B7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ValHDG, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ValHDG, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ValHDG, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);
// ui_font_OswaldM220 

ui_LblHDG = lv_label_create(ui_PanelTop);
lv_obj_set_width( ui_LblHDG, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LblHDG, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LblHDG, 150 );
lv_obj_set_y( ui_LblHDG, 80 );
lv_obj_set_align( ui_LblHDG, LV_ALIGN_CENTER );
lv_label_set_text(ui_LblHDG,"HDG");
lv_obj_set_style_text_color(ui_LblHDG, lv_color_hex(0xBAB7B7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LblHDG, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LblHDG, &lv_font_montserrat_34, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelSpeed = lv_obj_create(ui_ScreenRace);
lv_obj_set_height( ui_PanelSpeed, 265);
lv_obj_set_width( ui_PanelSpeed, lv_pct(100));
lv_obj_set_x( ui_PanelSpeed, -1 );
lv_obj_set_y( ui_PanelSpeed, lv_pct(3) );
lv_obj_set_align( ui_PanelSpeed, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelSpeed, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_PanelSpeed, lv_color_hex(0xBAB7B7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelSpeed, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_PanelSpeed, LV_BORDER_SIDE_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ValKTS = lv_label_create(ui_PanelSpeed);
lv_obj_set_width( ui_ValKTS, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ValKTS, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ValKTS, -10 );
lv_obj_set_y( ui_ValKTS, 5 );
lv_obj_set_align( ui_ValKTS, LV_ALIGN_CENTER );
lv_label_set_text(ui_ValKTS,"8.3");
lv_obj_set_style_text_color(ui_ValKTS, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ValKTS, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_ValKTS, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ValKTS, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);
// ui_font_OswaldM250

ui_LblKTS = lv_label_create(ui_PanelSpeed);
lv_obj_set_width( ui_LblKTS, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LblKTS, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LblKTS, 170 );
lv_obj_set_y( ui_LblKTS, 90 );
lv_obj_set_align( ui_LblKTS, LV_ALIGN_CENTER );
lv_label_set_text(ui_LblKTS,"KTS");
lv_obj_set_style_text_color(ui_LblKTS, lv_color_hex(0x010101), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LblKTS, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LblKTS, &lv_font_montserrat_34, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelBottom = lv_obj_create(ui_ScreenRace);
lv_obj_set_height( ui_PanelBottom, 230);
lv_obj_set_width( ui_PanelBottom, lv_pct(100));
lv_obj_set_x( ui_PanelBottom, 0 );
lv_obj_set_y( ui_PanelBottom, lv_pct(35) );
lv_obj_set_align( ui_PanelBottom, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelBottom, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_PanelBottom, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelBottom, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_PanelBottom, LV_BORDER_SIDE_NONE, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_heel = lv_obj_create(ui_PanelBottom);
lv_obj_remove_style_all(ui_heel);
lv_obj_set_width( ui_heel, lv_pct(50));
lv_obj_set_height( ui_heel, lv_pct(100));
lv_obj_set_align( ui_heel, LV_ALIGN_LEFT_MID );
lv_obj_clear_flag( ui_heel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ValHEEL = lv_label_create(ui_PanelBottom);
lv_obj_set_width( ui_ValHEEL, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ValHEEL, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ValHEEL, LV_ALIGN_LEFT_MID );
lv_obj_set_x( ui_ValHEEL, 60 );
lv_label_set_text(ui_ValHEEL,"10");
lv_obj_set_style_text_color(ui_ValHEEL, lv_color_hex(0xBAB7B7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ValHEEL, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ValHEEL, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);
// ui_font_OswaldM160

ui_LblHEEL = lv_label_create(ui_PanelBottom);
lv_obj_set_width( ui_LblHEEL, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LblHEEL, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LblHEEL, -35 );
lv_obj_set_y( ui_LblHEEL, -10 );
lv_obj_set_align( ui_LblHEEL, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_LblHEEL,"HEEL");
lv_obj_set_style_text_color(ui_LblHEEL, lv_color_hex(0xBAB7B7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LblHEEL, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LblHEEL, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LinhaSeparadora = lv_obj_create(ui_PanelBottom);
lv_obj_set_width( ui_LinhaSeparadora, 4);
lv_obj_set_height( ui_LinhaSeparadora, lv_pct(100));
lv_obj_set_align( ui_LinhaSeparadora, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_LinhaSeparadora, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_LinhaSeparadora, lv_color_hex(0xBAB7B7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LinhaSeparadora, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_LinhaSeparadora, lv_color_hex(0xBAB7B7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_color(ui_LinhaSeparadora, lv_color_hex(0xBAB7B7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_LinhaSeparadora, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_trim = lv_obj_create(ui_PanelBottom);
lv_obj_remove_style_all(ui_trim);
lv_obj_set_width( ui_trim, lv_pct(50));
lv_obj_set_height( ui_trim, lv_pct(100));
lv_obj_set_align( ui_trim, LV_ALIGN_RIGHT_MID );
lv_obj_clear_flag( ui_trim, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ValTRIM = lv_label_create(ui_PanelBottom);
lv_obj_set_width( ui_ValTRIM, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ValTRIM, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ValTRIM, LV_ALIGN_RIGHT_MID );
lv_obj_set_x( ui_ValTRIM, -60 ); 
lv_label_set_text(ui_ValTRIM,"3");
lv_obj_set_style_text_color(ui_ValTRIM, lv_color_hex(0xBAB7B7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ValTRIM, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ValTRIM, &lv_font_montserrat_48, LV_PART_MAIN| LV_STATE_DEFAULT);
// ui_font_OswaldM160

ui_LblTRIM = lv_label_create(ui_PanelBottom);
lv_obj_set_width( ui_LblTRIM, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LblTRIM, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LblTRIM, 35 );
lv_obj_set_y( ui_LblTRIM, -10 );
lv_obj_set_align( ui_LblTRIM, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_LblTRIM,"TRIM");
lv_obj_set_style_text_color(ui_LblTRIM, lv_color_hex(0xBAB7B7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LblTRIM, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LblTRIM, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

uic_LblHDG = ui_LblHDG;

}

void ui_ScreenRace_screen_destroy(void)
{
   if (ui_ScreenRace) lv_obj_del(ui_ScreenRace);

// NULL screen variables
ui_ScreenRace= NULL;
ui_PanelHeader= NULL;
ui_ValTime= NULL;
ui_ValTimer= NULL;
ui_ValBattery= NULL;
ui_PanelTop= NULL;
ui_ValHDG= NULL;
uic_LblHDG= NULL;
ui_LblHDG= NULL;
ui_PanelSpeed= NULL;
ui_ValKTS= NULL;
ui_LblKTS= NULL;
ui_PanelBottom= NULL;
ui_heel= NULL;
ui_ValHEEL= NULL;
ui_LblHEEL= NULL;
ui_LinhaSeparadora= NULL;
ui_trim= NULL;
ui_ValTRIM= NULL;
ui_LblTRIM= NULL;

}
